### ISSUE TITLE
你好，想问下您具体的cuda版本号以及python和pytorch版本

### ISSUE THREAD

**Issue by LeXueTao** [TBI805/DSNT#1]
最近一直在跑纯transoformer模型，一直到不了130，看到许多论文包括您这篇，结果对比中transformer都可以跑到131左右，特别疑惑，请问您以前遇到过这种问题吗？谢谢！！

**Comment by TBI805** [comment]
> 最近一直在跑纯transoformer模型，一直到不了130，看到许多论文包括您这篇，结果对比中transformer都可以跑到131左右，特别疑惑，请问您以前遇到过这种问题吗？谢谢！！

cuda11.2，torch1.8，Python3.6

你跑的你自己实现的代码还是直接跑的别人写好的代码呢？有些代码实现细节的不同，超参数啥的，可能会影响结果。

以前我没遇到过这样的问题，之前跑纯transformer都可以跑这么多，特征是用的ResNeXt101(Grid)

**Comment by LeXueTao** [comment]
谢谢您的回复，我也是用的ResNeXt101，代码是别人论文代码中附带的，我的结果只能将近127左右，太低了，我用的torch版本和python版本比较高，我降版本试试看，谢谢！

**Comment by LeXueTao** [comment]
您好，可以加个联系方式吗？有一些问题想找您咨询一下，新手一个，我在这留下我的微信号：Stu_Monster。谢谢，麻烦您了！！
