### ISSUE TITLE
你好，请问可以分享用在online test的 val 和 test json 文件吗？ 

### ISSUE THREAD

**Issue by Hianghua** [TBI805/DSNT#3]

**Comment by TBI805** [comment]
> 

test_online.py 可以直接生成val和test的json文件，只需要选择好相应的feature，annotation，pth文件的路径即可。

**Comment by Hianghua** [comment]
> > 
> 
> test_online.py 可以直接生成val和test的json文件，只需要选择好相应的feature，annotation，pth文件的路径即可。

您好， 我还有个问题想请教您

您上传的 test_online.py 文件里有好几个 ensemble 模型(line 55~60), 我也找了好几个公开代码，但是没有找到如何去训练 ensemble 模型的有关内容

想问ensemble 模型是不是就是换 random seed 反复训练得到性能组好的几个
或者是 其实代码有被公开，然而我没找到是哪个部分

**Comment by Hianghua** [comment]
> > 
> 
> test_online.py 可以直接生成val和test的json文件，只需要选择好相应的feature，annotation，pth文件的路径即可。

真心感谢您的回复！ 在这个地方卡了快3周了！ 感谢！！

**Comment by TBI805** [comment]
> > > 
> > 
> > test_online.py 可以直接生成val和test的json文件，只需要选择好相应的feature，annotation，pth文件的路径即可。
> 
> 您好， 我还有个问题想请教您
> 
> 您上传的 test_online.py 文件里有好几个 ensemble 模型(line 55~60), 我也找了好几个公开代码，但是没有找到如何去训练 ensemble 模型的有关内容
> 
> 想问ensemble 模型是不是就是换 random seed 反复训练得到性能组好的几个
> 或者是 其实代码有被公开，然而我没找到是哪个部分

是的，用不同的随机种子分别训练4个pth文件就行了，这里论文中的experiments部分也有说明（大概在online evaluation那一小节）

**Comment by Hianghua** [comment]
> > > > 
> > > 
> > > 
> > > test_online.py 可以直接生成val和test的json文件，只需要选择好相应的feature，annotation，pth文件的路径即可。
> > 
> > 
> > 您好， 我还有个问题想请教您
> > 您上传的 test_online.py 文件里有好几个 ensemble 模型(line 55~60), 我也找了好几个公开代码，但是没有找到如何去训练 ensemble 模型的有关内容
> > 想问ensemble 模型是不是就是换 random seed 反复训练得到性能组好的几个
> > 或者是 其实代码有被公开，然而我没找到是哪个部分
> 
> 是的，用不同的随机种子分别训练4个pth文件就行了，这里论文中的experiments部分也有说明（大概在online evaluation那一小节）

收到！ 祝您新的一年学业有成，SCI多多，发财暴富！

**Comment by TBI805** [comment]
> > > > > 
> > > > 
> > > > 
> > > > test_online.py 可以直接生成val和test的json文件，只需要选择好相应的feature，annotation，pth文件的路径即可。
> > > 
> > > 
> > > 您好， 我还有个问题想请教您
> > > 您上传的 test_online.py 文件里有好几个 ensemble 模型(line 55~60), 我也找了好几个公开代码，但是没有找到如何去训练 ensemble 模型的有关内容
> > > 想问ensemble 模型是不是就是换 random seed 反复训练得到性能组好的几个
> > > 或者是 其实代码有被公开，然而我没找到是哪个部分
> > 
> > 是的，用不同的随机种子分别训练4个pth文件就行了，这里论文中的experiments部分也有说明（大概在online evaluation那一小节）
> 
> 收到！ 祝您新的一年学业有成，SCI多多，发财暴富！
> 

谢谢，也祝您科研顺利！有问题随时交流
